#!/usr/bin/env python3
"""
Generate a synthetic full-scale 23andMe-style raw genotype file for testing.

- ~620,000 SNPs (passes app's minimum variant check)
- All PGS Catalog SNPs from bundled weights included with valid genotypes
- No real individual's data — safe for public repositories

Usage:
  python3 scripts/generate_test_genotype.py

Outputs:
  fixtures/synthetic-23andme-raw.txt
  fixtures/synthetic-23andme-raw.zip
"""

from __future__ import annotations

import gzip
import json
import random
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRS_DIR = ROOT / "src" / "data" / "prs"
OUT_DIR = ROOT / "fixtures"
PUBLIC_DIR = ROOT / "public" / "test-data"
TXT_NAME = "synthetic-23andme-raw.txt"
ZIP_NAME = "synthetic-23andme-raw.zip"
TARGET_VARIANTS = 620_000
RNG_SEED = 42


def load_prs_variants() -> dict[str, dict]:
    """rsid -> {chr, pos, effect, other} from bundled JSON weights."""
    by_rsid: dict[str, dict] = {}
    for path in sorted(PRS_DIR.glob("*.json")):
        with open(path) as f:
            data = json.load(f)
        for v in data.get("variants", []):
            rsid = v["rsid"].lower()
            by_rsid[rsid] = {
                "chr": str(v.get("chr") or "1"),
                "pos": int(v.get("pos") or 1_000_000),
                "effect": v["effectAllele"][0].upper(),
                "other": (v["otherAllele"] or "G")[0].upper(),
            }
    return by_rsid


def genotype_for_prs(effect: str, other: str, rng: random.Random) -> str:
    """Random valid diploid genotype using effect/other alleles."""
    dosage = rng.choice([0, 0, 1, 1, 2])  # skew toward reference
    if dosage == 0:
        return other + other
    if dosage == 2:
        return effect + effect
    return effect + other if rng.random() < 0.5 else other + effect


def write_header(f) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    f.write(f"# This data file generated by PRS Screen test fixture generator at: {now}\n")
    f.write("# Synthetic data — NOT from a real person. For development and CI only.\n")
    f.write("# https://github.com/vmbharanidharan-ai/PRS_test\n")
    f.write("#\n")
    f.write("# rsid\tchromosome\tposition\tgenotype\n")


def generate_synthetic_pool(
    rng: random.Random,
    count: int,
    exclude: set[str],
) -> list[tuple[str, str, int, str]]:
    alleles = ["A", "C", "G", "T"]
    chroms = [str(i) for i in range(1, 23)] + ["X", "Y", "MT"]
    rows: list[tuple[str, str, int, str]] = []
    rs_num = 1_000_000
    while len(rows) < count:
        rsid = f"rs{rs_num}"
        rs_num += 1
        if rsid in exclude:
            continue
        chrom = rng.choice(chroms)
        pos = rng.randint(10_000, 250_000_000)
        g1, g2 = rng.choice(alleles), rng.choice(alleles)
        rows.append((rsid, chrom, pos, g1 + g2))
    return rows


def main() -> None:
    rng = random.Random(RNG_SEED)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    prs = load_prs_variants()
    print(f"Loaded {len(prs)} unique PRS SNPs from bundled weights")

    prs_rows: list[tuple[str, str, int, str]] = []
    for rsid, meta in sorted(prs.items()):
        gt = genotype_for_prs(meta["effect"], meta["other"], rng)
        prs_rows.append((rsid, meta["chr"], meta["pos"], gt))

    filler_count = max(0, TARGET_VARIANTS - len(prs_rows))
    filler = generate_synthetic_pool(rng, filler_count, set(prs.keys()))
    all_rows = prs_rows + filler
    rng.shuffle(all_rows)

    txt_path = OUT_DIR / TXT_NAME
    with open(txt_path, "w") as f:
        write_header(f)
        for rsid, chrom, pos, gt in all_rows:
            f.write(f"{rsid}\t{chrom}\t{pos}\t{gt}\n")

    zip_path = OUT_DIR / ZIP_NAME
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(txt_path, arcname=TXT_NAME)

    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
    public_zip = PUBLIC_DIR / ZIP_NAME
    public_zip.write_bytes(zip_path.read_bytes())

    gz_path = OUT_DIR / (TXT_NAME + ".gz")
    with open(txt_path, "rb") as fin, gzip.open(gz_path, "wb") as fout:
        fout.writelines(fin)

    size_mb = txt_path.stat().st_size / 1_000_000
    zip_mb = zip_path.stat().st_size / 1_000_000
    print(f"Wrote {txt_path} ({len(all_rows):,} variants, {size_mb:.1f} MB)")
    print(f"Wrote {zip_path} ({zip_mb:.1f} MB)")
    print(f"Wrote {public_zip} (web download at /test-data/{ZIP_NAME})")
    print(f"Wrote {gz_path}")


if __name__ == "__main__":
    main()
